### ISSUE TITLE
500 when trying to create draft dmp

### ISSUE THREAD

**Issue by rsmith013** [cedadev/django-dmp#43]
```[ERROR] [2021-02-12 12:46:01,345] [django.request:228] [waitress-2] Internal Server Error: /dmp/project/917
Traceback (most recent call last):
  File "/home/waitress/venv/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/waitress/venv/lib64/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/waitress/venv/lib64/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/lib64/python3.6/contextlib.py", line 52, in inner
    return func(*args, **kwds)
  File "/home/waitress/venv/lib64/python3.6/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/home/waitress/src/django_dmp/dmp/views.py", line 302, in dmp_draft
    if token.token_expiry < datetime.datetime.now():
TypeError: can't compare offset-naive and offset-aware datetimes
```

**Comment by rsmith013** [comment]
closed by #9c37aaefa202894efb16c128072f98722049097a
